INSERT INTO scored_trends (trend_name, platform, trend_type, emotional_hook, spike_pct, chivas_score, absolut_score, jameson_score, glenlivet_score, top_brand, opportunity_note, content_angle, source_url, week_number, year) VALUES
('#BartenderPOV', 'tiktok', 'format', 'Behind-the-bar POV going viral, aspirational and crafty', 420, 4, 3, 5, 3, 'Jameson', 'Jump on POV format with Jameson cocktail prep', 'First-person bar shift reel, real and unscripted', 'https://www.tiktok.com/@barmanship/video/7312098765432109876', 25, 2026),
('#DubaiNightlife', 'tiktok', 'hashtag', 'FOMO-driven rooftop highlights, luxury and aspirational', 180, 5, 4, 2, 3, 'Chivas Regal', 'Own the rooftop moment with Chivas as the drink of success', 'Slow-mo golden hour Chivas pour on Dubai skyline', 'https://www.tiktok.com/@dubaidiaries/video/7298341256789012345', 25, 2026),
('Cocktail Cinematic Reel', 'instagram', 'format', 'Hyper-aesthetic pour shots with moody lighting, feels premium', 210, 5, 3, 2, 4, 'Chivas Regal', 'Lead the aesthetic with Chivas cinematic pour content', 'Ultra slow-mo Chivas pour, moody lighting, no voiceover', 'https://www.instagram.com/reel/C8kL2xMoP4N/', 25, 2026),
('#GinAndTonic Challenge', 'tiktok', 'audio', 'Vibrant colourful city energy, people showing their G&T builds', 260, 2, 4, 3, 2, 'Absolut Vodka', 'Hijack trend and swap gin for Absolut in a bold creative twist', 'Creator-style recipe reel swapping gin for Absolut', 'https://www.tiktok.com/@cocktailchemistry/video/7289654321098765432', 25, 2026),
('#SlowMomentsCampaign', 'tiktok', 'hashtag', 'Savoring the moment, golden hour, glass in hand, no rush', 340, 5, 2, 3, 4, 'Chivas Regal', 'Perfect brand fit, Chivas slow down ethos matches this trend', 'Single static shot, Chivas glass, golden light, pure mood', 'https://www.tiktok.com/@h_the_bartender/video/7316547823941289242', 25, 2026),
('Premium Scotch Unboxing', 'instagram', 'format', 'Gift reveal, luxury packaging, suspense and gifting culture', 145, 5, 1, 2, 5, 'The Glenlivet', 'Glenlivet gift sets are perfect for this unbox format', 'Unboxing Glenlivet gift set with tissue paper and card reveal', 'https://www.instagram.com/reel/C9pX3kLmN8Q/', 25, 2026),
('#AbuDhabiNights', 'tiktok', 'hashtag', 'Abu Dhabi luxury scene, sophisticated and aspirational GCC', 195, 5, 3, 2, 4, 'Chivas Regal', 'Position Chivas as the drink of Abu Dhabi luxury occasions', 'Chivas at Abu Dhabi venue, prestige and brotherhood', 'https://www.tiktok.com/@uaelifestyle_/video/7301234567891234567', 25, 2026),
('Artful Pour Series', 'instagram', 'format', 'Creative and abstract, cocktail making as visual art form', 115, 3, 5, 2, 3, 'Absolut Vodka', 'Absolut art direction is natural with bold expressive pour', 'Abstract Absolut cocktail art reel with overhead pour', 'https://www.instagram.com/reel/C6tY4nMoR1S/', 25, 2026),
('Everyone Welcome Pub Night', 'instagram', 'format', 'Inclusive warm unscripted gatherings, real people real laughs', 95, 2, 3, 5, 1, 'Jameson', 'Jameson everyone welcome ethos is this trend, own it now', 'Unscripted group toast video, Jameson, friends, zero production', 'https://www.instagram.com/reel/C7mN8pQrS2T/', 25, 2026),
('Irish Warmth Reel Format', 'instagram', 'format', 'Friendship toasts, group laughs, pub-style warmth, zero pretense', 88, 2, 2, 5, 1, 'Jameson', 'Authentic Jameson content, real moments and pub energy', 'UGC-style Jameson toast reel, warm real pub atmosphere', 'https://www.instagram.com/reel/C5sW7mNpQ3T/', 25, 2026);
